# Site settings
title: 华东师范大学<br>冰冻圈科学研究荟
header-img: "img/top.png"
tagline: "cn"  
description: "深挖洞、广积粮"  
baseurl: ""
url: "http://cryoecnu.github.io"  

# About/contact
owner: 
  name: "CryoECNU"
  email: wangkang1984@gmail.com
  bio: "Write what I want to write"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

douban_username:  
twitter_username: 
github_username: 
facebook_username: 
weibo_username: 
zhihu_username: 

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: America/Denver

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "CryoECNU"
      header-img: "img/top.png" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : 
  disqus :
      short_name : 

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
# Friends
friends: [
{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
theme: jekyll-theme-slate